# Generated by Django 5.0.8 on 2026-05-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Ex: CV_CREATED, PDF_EXPORTED, LOGIN', max_length=255)),
                ('app_label', models.CharField(help_text="L'application concernée", max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires au format JSON')),
            ],
            options={
                'verbose_name': 'Activité Utilisateur',
                'verbose_name_plural': 'Activités Utilisateurs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
