# Generated by Django 5.0.8 on 2026-05-03 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBSCRIPTION', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['order', 'price']},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('month', 'Mensuel'), ('year', 'Annuel')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage pour les plans, du plus populaire au plus avancé."),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='ID du prix Stripe. Permet de gérer le paiement récurrent via Stripe Checkout.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('active', 'Actif'), ('canceled', 'Annulé'), ('expired', 'Expiré')], default='pending', max_length=20),
        ),
    ]
